import 'package:flutter/material.dart';
import 'package:flutter_animate/flutter_animate.dart';
import 'package:google_fonts/google_fonts.dart';
import '../core/theme.dart';

class FaqScreen extends StatelessWidget {
  const FaqScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final faqs = [
      {
        'q': 'How does FAKeless protect my voice?',
        'a': 'FAKeless modifies your audio file using an invisible acoustic watermark. To humans, it sounds entirely normal. However, if someone tries to use this protected audio to train an AI voice clone or feed it into a voice conversion system, the watermark severely disrupts the AI, causing the clone output to be garbled and unusable.'
      },
      {
        'q': 'Which protection scale should I use?',
        'a': 'Scale 1 (Minimal) is best if audio quality is paramount and you are sharing with trusted friends. Scale 5 (Maximum) offers the most aggressive distortion against AI cloners and is recommended for sensitive public uploads. The "Standard" setting (Scale 3) offers the best balance for most users. You can also ask the AI Guard for a recommendation!'
      },
      {
        'q': 'What happens if I lose internet connection?',
        'a': 'FAKeless comes with a Local Fallback Mode. If the primary cloud protection server is unreachable, the app automatically switches to an on-device, lightweight AI model based on TensorFlow Lite to provide offline protection.'
      },
      {
        'q': 'Is my audio uploaded or saved online?',
        'a': 'No. Cloud protection processes the audio statelessly and securely deletes it immediately after the watermark is applied. FAKeless prioritizes your privacy above all.'
      },
      {
        'q': 'What does PESQ and STOI mean?',
        'a': 'PESQ (Perceptual Evaluation of Speech Quality) measures how natural your audio sounds after protection, similar to what a human would rate it. STOI (Short-Time Objective Intelligibility) measures how easy it is to understand the words in the audio. Higher scores mean better quality is preserved.'
      },
      {
        'q': 'Does FAKeless work with deepfake detection?',
        'a': 'Yes! The new "Detect" tab allows you to check if any audio file has been generated by an AI voice cloner, allowing you to easily verify voice legitimacy.'
      },
      {
        'q': 'Will the watermark be affected by compression?',
        'a': 'FAKeless watermarks are designed to be robust against common compressions (like WhatsApp or MP3 conversion). However, heavy compression might slightly reduce the defensive effectiveness. Always keep your original protected .WAV for the highest security.'
      },
    ];

    return Scaffold(
      backgroundColor: AppTheme.background,
      body: CustomScrollView(
        slivers: [
          SliverAppBar(
            pinned: true,
            backgroundColor: AppTheme.background,
            title: Text('Help & FAQ',
                style: GoogleFonts.inter(
                    color: AppTheme.cyanAccent,
                    fontWeight: FontWeight.w700,
                    fontSize: 18,
                    letterSpacing: 1)),
          ),
          SliverPadding(
            padding: const EdgeInsets.fromLTRB(20, 12, 20, 100),
            sliver: SliverList(
              delegate: SliverChildListDelegate([
                _Header(),
                const SizedBox(height: 24),
                ...faqs.asMap().entries.map((e) {
                  final delay = (e.key * 80).ms;
                  return _FaqItem(q: e.value['q']!, a: e.value['a']!)
                      .animate().slideY(begin: 0.1, delay: delay).fadeIn(delay: delay);
                }).toList(),
              ]),
            ),
          ),
        ],
      ),
    );
  }
}

class _Header extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: AppTheme.cyanAccent.withOpacity(0.08),
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: AppTheme.cyanAccent.withOpacity(0.3)),
      ),
      child: Row(
        children: [
          const Icon(Icons.help_center, color: AppTheme.cyanAccent, size: 40),
          const SizedBox(width: 16),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text('Got Questions?', style: GoogleFonts.inter(color: AppTheme.textMain, fontWeight: FontWeight.w800, fontSize: 18)),
                const SizedBox(height: 4),
                Text('Learn how FAKeless keeps your voice safe from AI identity theft.', style: GoogleFonts.inter(color: AppTheme.textSecondary, fontSize: 12)),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

class _FaqItem extends StatelessWidget {
  final String q;
  final String a;
  const _FaqItem({required this.q, required this.a});

  @override
  Widget build(BuildContext context) {
    return Container(
      margin: const EdgeInsets.only(bottom: 12),
      decoration: BoxDecoration(
        gradient: AppTheme.cardGradient,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: AppTheme.surfaceHigh),
      ),
      child: Theme(
        data: Theme.of(context).copyWith(dividerColor: Colors.transparent),
        child: ExpansionTile(
          iconColor: AppTheme.cyanAccent,
          collapsedIconColor: AppTheme.textSecondary,
          title: Text(q, style: GoogleFonts.inter(color: AppTheme.textMain, fontWeight: FontWeight.w600, fontSize: 14)),
          children: [
            Padding(
              padding: const EdgeInsets.fromLTRB(16, 0, 16, 16),
              child: Text(a, style: GoogleFonts.inter(color: AppTheme.textSecondary, fontSize: 13, height: 1.5)),
            ),
          ],
        ),
      ),
    );
  }
}
